image:
  repository: openelevation/open-elevation
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

data:
  mountPath: /code/data

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: elevation.local
      paths:
        - path: /
          pathType: Prefix

persistence:
  enabled: true
  existingClaim: ""
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 1Gi
  keepOnUninstall: false

dataset:
  enabled: true
  skipIfDataPresent: true
  urls: []
  tile:
    enabled: false
    xTiles: 10
    yTiles: 10
    removeSourceAfterTiling: true
  cleanupArchives: true

tolerations:
- key: "layer"
  operator: "Equal"
  value: "infra"
  effect: "NoSchedule"

env: {}
